print("Integer")
print(6)
print("\n")
print("Float")
print(3.8)
print("\n")
print("Complex")
print(6+26j)
print("\n")
print("String")
print("Hola")
print("\n")
print("Boolean")
print(False)
print("\n")
print("List")
print([1, 2, 3])
print("\n")
print("Tuple")
print((9.8, 3.14, 2.7))
print("\n")
print("Set")
print({9.8, 3.14, 2.7})
print("\n")
print("Dictionary")
print({'nombre':'Luis'})

import math
x1, y1 = 2, 3
x2, y2 = 10, 8
distance = math.sqrt((x2 - x1)**2 + (y2 - y1)**2)
print("Euclidean distance:",distance)